feat: 添加 norelease 文件到 fn-aic8800、fn-broadcom-sta、fn-yt6801 和 fn-ntfs3

diff --git a/fn-aic8800/cmd/main b/fn-aic8800/cmd/main
--- a/fn-aic8800/cmd/main
+++ b/fn-aic8800/cmd/main
@@ -10,6 +10,24 @@ log_msg() {
   echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >>${LOG_FILE}
 }
 
+check_with_build() {
+  if [ ! -f "${TRIM_APPDEST}/server/src/aic8800_fdrv/aic8800_fdrv.ko" ]; then
+    echo "Module file not found: ${TRIM_APPDEST}/server/src/aic8800_fdrv/aic8800_fdrv.ko" >>${LOG_FILE}
+    . "$(dirname "$0")/install_callback" >>${LOG_FILE}
+    return $?
+  fi
+
+  vermagic_module=$(modinfo -F vermagic "${TRIM_APPDEST}/server/src/aic8800_fdrv/aic8800_fdrv.ko" 2>/dev/null | awk '{printf $1}')
+  vermagic_kernel=$(uname -r)
+  if [ "${vermagic_module}" != "${vermagic_kernel}" ]; then
+    echo "Module vermagic (${vermagic_module}) does not match kernel version (${vermagic_kernel})" >>${LOG_FILE}
+    . "$(dirname "$0")/install_callback" >>${LOG_FILE}
+    return $?
+  fi
+
+  return 0
+}
+
 insmod_from_file() {
   [ -z "${1}" ] && return 1
   local module_file module_name dep_modules
@@ -50,6 +68,7 @@ start_process() {
   fi
 
   log_msg "Starting process ..."
+	check_with_build || return 1
   [ -L "/usr/lib/udev/rules.d/50-usb-aic-net.rules" ] && rm -f "/usr/lib/udev/rules.d/50-usb-aic-net.rules"
   [ ! -L "/usr/lib/udev/rules.d/50-usb-aic-net.rules" ] && ln -s "${TRIM_APPDEST}/server/udev/50-usb-aic-net.rules" "/usr/lib/udev/rules.d/50-usb-aic-net.rules"
   udevadm control --reload-rules
diff --git a/fn-broadcom-sta/cmd/main b/fn-broadcom-sta/cmd/main
--- a/fn-broadcom-sta/cmd/main
+++ b/fn-broadcom-sta/cmd/main
@@ -10,6 +10,24 @@ log_msg() {
   echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >>${LOG_FILE}
 }
 
+check_with_build() {
+  if [ ! -f "${TRIM_APPDEST}/server/src/wl.ko" ]; then
+    echo "Module file not found: ${TRIM_APPDEST}/server/src/wl.ko" >>${LOG_FILE}
+    . "$(dirname "$0")/install_callback" >>${LOG_FILE}
+    return $?
+  fi
+
+  vermagic_module=$(modinfo -F vermagic "${TRIM_APPDEST}/server/src/wl.ko" 2>/dev/null | awk '{printf $1}')
+  vermagic_kernel=$(uname -r)
+  if [ "${vermagic_module}" != "${vermagic_kernel}" ]; then
+    echo "Module vermagic (${vermagic_module}) does not match kernel version (${vermagic_kernel})" >>${LOG_FILE}
+    . "$(dirname "$0")/install_callback" >>${LOG_FILE}
+    return $?
+  fi
+
+  return 0
+}
+
 insmod_from_file() {
   [ -z "${1}" ] && return 1
   local module_file module_name dep_modules
@@ -50,6 +68,7 @@ start_process() {
   fi
 
   log_msg "Starting process ..."
+	check_with_build || return 1
   modprobe -r b43 b43legacy b44 bcma brcm80211 brcmsmac ssb >>${LOG_FILE} 2>&1
   insmod_from_file "${TRIM_APPDEST}/server/src/wl.ko" >>${LOG_FILE} 2>&1
   return 0
