feat: fn-wifi-hotspot，添加 Wi-Fi 驱动和功率检查功能，优化热点配置流程

diff --git a/fn-wifi-hotspot/cmd/install_callback b/fn-wifi-hotspot/cmd/install_callback
--- a/fn-wifi-hotspot/cmd/install_callback
+++ b/fn-wifi-hotspot/cmd/install_callback
@@ -6,15 +6,16 @@ chmod +x ${TRIM_APPDEST}/ui/*.cgi 2>/dev/null || true
 chmod +x ${TRIM_APPDEST}/www/cgi-bin/*.cgi 2>/dev/null || true
 chmod +x ${TRIM_APPDEST}/www/cgi-bin/*.sh 2>/dev/null || true
 
-for F in "/usr/lib/firmware/regulatory.db" "/usr/lib/firmware/regulatory.db.p7s"; do
-  if [ "$(readlink -f "${F}")" = "${F}-debian" ] && [ -f "${F}-upstream" ]; then
-    rm -f "${F}"
-    ln -vsf "${F}-upstream" "${F}"
-    [ $? -ne 0 ] && {
-      echo "Failed to link ${F}-upstream to ${F}" >$TRIM_TEMP_LOGFILE
-      exit 1
-    }
-  fi
-done
+# fnOS v1.1.28 Fix regulatory.db issue
+# for F in "/usr/lib/firmware/regulatory.db" "/usr/lib/firmware/regulatory.db.p7s"; do
+#   if [ "$(readlink -f "${F}")" = "${F}-debian" ] && [ -f "${F}-upstream" ]; then
+#     rm -f "${F}"
+#     ln -vsf "${F}-upstream" "${F}"
+#     [ $? -ne 0 ] && {
+#       echo "Failed to link ${F}-upstream to ${F}" >$TRIM_TEMP_LOGFILE
+#       exit 1
+#     }
+#   fi
+# done
 
 exit 0
